on: [push, pull_request]
name: Run Tests
jobs:
  test:
    strategy:
      matrix:
        node-version: [10, 12, 14]
        platform: [ubuntu-latest, macos-latest, windows-latest]
    runs-on: ${{ matrix.platform }}

    steps:
      - uses: actions/checkout@v2

      - name: Install NodeJS
        uses: actions/setup-node@v1
        with:
          node-version: ${{ matrix.node-version }}

      - name: Install Dependencies
        run: npm i

      - name: Test
        run: npm test
